Phrack fixed their site.

diff --git a/phrack b/phrack
--- a/phrack
+++ b/phrack
@@ -28,13 +28,21 @@ _update_progress() {
 _download_file() {
     local url="$1"
     local output_file="$2"
+    local retcode=0
     if command -v wget >/dev/null 2>&1; then
-        wget --no-check-certificate --cipher SECURE128 -q "$url" -O "$output_file"
+        wget -q "$url" -O "$output_file"
+        retcode=$?
     elif command -v curl >/dev/null 2>&1; then
-        curl -sSL --insecure --ciphers SECURE128 "$url" -o "$output_file"
+        curl -sSL "$url" -o "$output_file"
+        retcode=$?
     else
         echo "Error: Neither wget nor curl is available. Please install one of them." >&2
-        return 1
+        exit 1
+    fi
+
+    if [ $retcode -ne 0 ]; then
+        echo "Failed to download $url" >&2
+        exit 1
     fi
 }
 
@@ -81,7 +89,7 @@ _download_archive() {
         INDEX_URL="https://phrack.org/archives/issues/"
         INDEX_FILE="index.html"
         _download_file "$INDEX_URL" "$INDEX_FILE"
-        NUM_ISSUES=$(grep -oP '(?<=<A HREF=")[0-9]+(?=/">)' "$INDEX_FILE" | sort -rn | head -n1)
+        NUM_ISSUES=$(grep -oP '(?<=/issues/)[0-9]+(?=/)' "$INDEX_FILE" | sort -rn | head -n1)
         rm "$INDEX_FILE"
 
         # Initialize progress file and create lock file
@@ -89,7 +97,7 @@ _download_archive() {
         touch "$PROGRESS_FILE.lock"
 
         # Await all tarball downloads to complete.
-        echo "Downloading $NUM_ISSUES to $DEST_DIR"
+        echo "Downloading $NUM_ISSUES issues to $DEST_DIR"
         for i in $(seq $NUM_ISSUES -1 1); do _download_all_files $i & done; wait
         echo
 
@@ -322,11 +330,11 @@ for arg in "$@"; do
             echo "  Read Phrack on the command line."
             exit 0
         ;;
-        -m|--miku|-_ooeeoo)
+        -m|--miku|-ooeeoo)
             _ooeeoo
             exit 0
         ;;
-        -m|--lain|--_love_lain)
+        -m|--lain|--love_lain)
             _love_lain
             exit 0
         ;;
